### ISSUE TITLE
Задачи на 3.06.2017

### ISSUE THREAD

**Issue by pltnm239** [pltnm239/bimvc#1]
- [x] BIM-менеджер
Самое главное - обновить страницу курса http://bim.vc/bimmanager/ 
Чтобы тебе было проще, я сверстал макет в Word, собрал исходные файлы.
Всё лежит тут: https://www.dropbox.com/sh/u2vp3xm41fakzwy/AADDUeRXOxoy4xZ2rLw8V1Ina?dl=0 

- [x] Кнопка "Новости" на ленте в шапке сайта, по расположению - наверное между Услуги и База знаний.
- [x] Если можно - то подредактировать шаблон страницы с новостями, кнопка Далее почти не видна
- [x] Сейчас показываются только 5 последних новостей - можно увеличить количество?

- [x] Сделали новый тест по Navis (ну да ты помнишь).
Не совсем понятно, как добавить его в Тестирования на общей странице Базы знаний и на страницу со списком тестов.

- [x] Добавить про обработку персональных данных
Обновить регистрацию, добавить согласие на обработку персональных данных, и прописать правила (типа чтобы люди могли ознакомиться, с чем соглашаются)
Ссылка на Тинькофф: https://journal.tinkoff.ru/personalnye-dannye/

**Comment by AVysotskiy** [comment]
Миша, посмотрел страницу БМ - всё классно) Замечаний всего 2 маленьких:

- можно ли в самом первом блоке ("В июле в Москве ... ... ... с коллегами) сделать меньше отступы: до абзаца и после абзаца. А то очень растянуто получается
- "Необходимые знания для прохождения" - перепутались местами блоки: слева Ревит, справа Навис. И подпись у Нависа обнови, пожалуйста :)

Вроде всё, спасибо!

**Comment by pltnm239** [comment]
> можно ли в самом первом блоке ("В июле в Москве ... ... ... с коллегами) сделать меньше отступы: до абзаца и после абзаца. А то очень растянуто получается
"Необходимые знания для прохождения" - перепутались местами блоки: слева Ревит, справа Навис. И подпись у Нависа обнови, пожалуйста :)

Готово!

**Comment by pltnm239** [comment]
> Сейчас показываются только 5 последних новостей - можно увеличить количество?

увеличил до 10

**Comment by pltnm239** [comment]
> Сделали новый тест по Navis (ну да ты помнишь).
> Не совсем понятно, как добавить его в Тестирования на общей странице Базы знаний и на страницу со списком тестов.

поменял тип сортировки и теперь последний добавленный тест будет выводится первым. На страницу Тестирование добавляется в ручную - автоматизирую этот процесс.

**Comment by pltnm239** [comment]
> Добавить про обработку персональных данных
> Обновить регистрацию, добавить согласие на обработку персональных данных, и прописать правила (типа чтобы люди могли ознакомиться, с чем соглашаются)
> Ссылка на Тинькофф: https://journal.tinkoff.ru/personalnye-dannye/

сделал страницу /agree (текст можно менять) и прописал пункт согласия при регистрации
